### PR TITLE
fix(tx-builder): Fixed long javascript numbers overflow in Arrays

### LINKED ISSUE #440: [TX-Builder] Arrays with long numbers cause overflow
## Description
When inputing an array of long numbers without wrapping as string they cause overflow.

This needs to be tested on an input that gets an array of u/int values.

## Environment
 - App: TX-Builder
 - Browser: All
 - Safe: All
 - Environment:
   - all

## Steps to reproduce
 1. Go to TX-Builder, using an ABI that requires uint, int or [uint], [int]
 2. Try to submit the form but an error will prevent with cause "overflow"

## Expected result
Transaction can be submited without issues

## Obtained result
Transaction is not possible to submit unless wrapping the values into strings

## Screenshots
imagen

### PR DESCRIPTION
**Pull request by DaniSomoza**
## What it solves
Resolves #440 

## How this PR fixes it

Added refactor to the solidity field types to fix the issue cause by long javascript numbers overflow in Arrays

Added unit tests to make sure that its fixed:

```
      describe('out of range javascript numbers issue', () => {
        it('validates out of range javascript numbers values', () => {
          const arrayOfIntsValidation = validateField('int[]')

          const validationResult = arrayOfIntsValidation(
            '[6426191757410075707, 6426191757410075707]',
          )

          expect(validationResult).toBe(NO_ERROR_IS_PRESENT)
        })

        it('validates out of range javascript numbers as string values', () => {
          const arrayOfIntsValidation = validateField('int[]')

          const validationResult = arrayOfIntsValidation(
            '["6426191757410075707", "6426191757410075707"]',
          )

          expect(validationResult).toBe(NO_ERROR_IS_PRESENT)
        })

        it('validates out of range javascript numbers as string and number values', () => {
          const arrayOfIntsValidation = validateField('int[2]')

          const validationResult = arrayOfIntsValidation(
            '["6426191757410075707", 6426191757410075707]',
          )

          expect(validationResult).toBe(NO_ERROR_IS_PRESENT)
        })
      })
```

## Testing Contracts

Gnosis Chain:
```
"BasicTypesTestContract" at 0x6E4B36F8aE70BE64161E93C015a4201a37D6BEB3
"MatrixTypesTestContract" at 0x4f5b7e34f8C629704D25a03aAFcB0C525fdfAC2E
```

Polygon:
```
"BasicTypesTestContract" at 0x80b874961edF68c1ee7a097688bBB93FFe6C4db1 
"MatrixTypesTestContract" at 0x6E4B36F8aE70BE64161E93C015a4201a37D6BEB3
```

Rinkeby:
```
"BasicTypesTestContract" at 0xD7b9B6c7DCbC7F95F06e1Bc1e7894530b066EB23
"MatrixTypesTestContract" at 0x56f4Dd7c3fd04E277Bd94B5e6764dd00a46c1B94
```

Goerli:
```
"BasicTypesTestContract" at 0x51A099ac1BF46D471110AA8974024Bfe518Fd6C4 
"MatrixTypesTestContract" at 0x32a513CEa8d897988FAbDb9dc5Fa836bF6144F5e
```

Volta:
```
"BasicTypesTestContract" at 0xfA416bc753e660dc1C570aBCf1bcC43C36c625B4 
"MatrixTypesTestContract" at 0x9Fac0596D305dBc72992a3B45f4f17791bCbC9Ee
```

### CODE REVIEW

File: apps/tx-builder/src/scripts/deploy-test-basic-contract.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
+const RINKEBY_ETHERSCAN_URL = 'https://rinkeby.etherscan.io'
```
Comment (mikhailxyz) [inline apps/tx-builder/src/scripts/deploy-test-basic-contract.js:1]: would be great to have it as an environment variable in case we want to deploy it on another chain

File: apps/tx-builder/src/scripts/deploy-test-matrix-contract.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+  console.log('')
+
+  console.log('Matrix Test Contract Address: ', testContractAddress)
+  console.log('')
+
+  const etherscanUrl = `${RINKEBY_ETHERSCAN_URL}/address/${testContractAddress}`
+  console.log('Etherscan URL: ', etherscanUrl)
+  console.log('')
+
+  const verifyCommand = `yarn contract:verify:rinkeby ${testContractAddress}`
```
Comment (mikhailxyz) [inline apps/tx-builder/src/scripts/deploy-test-matrix-contract.js:24]: you can also compose deployment & verification into hardhat tasks like in safe-contracts: https://github.com/safe-global/safe-contracts/blob/main/src/tasks/deploy_contracts.ts

File: apps/tx-builder/src/scripts/deploy-test-basic-contract.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+const TEST_CONTRACT_NAME = 'BasicTypesTestContract'
+
+async function main() {
```
Comment (mikhailxyz) [inline apps/tx-builder/src/scripts/deploy-test-basic-contract.js:4]: would be great to add the deploy plugin sometime: https://github.com/wighawag/hardhat-deploy/tree/master

It'd deploy the contract to the same address across all the networks

File: apps/tx-builder/src/scripts/read-test-contract-value.js [hunk 4]
```diff
@@ -0,0 +1,32 @@
+const RINKEBY_ETHERSCAN_URL = 'https://rinkeby.etherscan.io'
```
Comment (mikhailxyz) [inline apps/tx-builder/src/scripts/read-test-contract-value.js:1]: would be cool to mention this scripts in docs

**Review by mikhailxyz — APPROVED** [review]
Damn what a monster, great job ser

Few nitpicks

File: apps/tx-builder/src/utils.test.ts [hunk 5]
```diff
@@ -0,0 +1,1506 @@
...
+        expect(
+          parseInputValue(tupleFieldType, '["6426191757410075707","6426191757410075707"]'),
+        ).toEqual(['6426191757410075707', '6426191757410075707'])
+        // FIX: fix the issue with long numbers in tuples
+        expect(
+          parseInputValue(tupleFieldType, '[6426191757410075707,6426191757410075707]'),
+        ).toEqual(['6426191757410075707', '6426191757410075707'])
+      })
+
+      it.skip('parses a tuple with nested tuples with long int values', () => {
```
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/utils.test.ts:679]: I skipped this test because the issue with long numbers in tuples will be fixed in this other ticket: https://github.com/safe-global/safe-react-apps/issues/448

I added this comment below:
```
        // FIX: fix the issue with long numbers in tuples
```

File: apps/tx-builder/src/utils.test.ts [hunk 6]
```diff
@@ -0,0 +1,1506 @@
...
+        it('parse an empty array as valid value', () => {
+          expect(parseInputValue('uint[]', '[]')).toEqual([])
+          expect(parseInputValue('uint[2]', '[]')).toEqual([])
+
+          expect(parseInputValue('uint120[]', '[]')).toEqual([])
+          expect(parseInputValue('uint120[2]', '[]')).toEqual([])
+        })
+
+        it('parse an invalid array throws a SyntaxError', () => {
+          expect(() => parseInputValue('uint[]', 'invalid_array_value')).toThrow(SyntaxError)
```
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/utils.test.ts:489]: I selected the `SyntaxError` because `JSON.parse()` throws a `SyntaxError` exception if the string to parse is not valid JSON.

But we can change it, what error can we throw ?

[the remark this answers is not in the document]
Comment (mikhailxyz) [reply apps/tx-builder/src/utils.test.ts:489]: perhaps a custom error like `SoliditySyntaxError` or something like that to highlight that the error is not thrown by the JS engine but by us

File: apps/tx-builder/src/components/forms/fields/Field.tsx [hunk 7]
```diff
@@ -75,8 +63,8 @@ const Field = ({
   validations, // you can define extra validations as a prop
   ...props
 }: FieldProps) => {
-  // Component based on field type
-  const Component = CUSTOM_SOLIDITY_COMPONENTS[fieldType] || TextContractField
+  // Component based on the field type
+  const FieldComponent = getFieldComponent(fieldType)
```
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/components/forms/fields/Field.tsx:67]: I tested it and it seems that it is not recreated every render:

Captura de pantalla 2022-06-08 a las 11 46 19
Captura de pantalla 2022-06-08 a las 11 46 27

And I changed the value of the field and clicked on Custom data switch to trigger multiple renders and it seems that the unmount is not happening:
Captura de pantalla 2022-06-08 a las 11 46 06

File: apps/tx-builder/src/scripts/deploy-test-basic-contract.js (hunk 1 above)
Comment (DaniSomoza) [reply apps/tx-builder/src/scripts/deploy-test-basic-contract.js:1]: good catch! I will update it!

File: apps/tx-builder/src/scripts/deploy-test-matrix-contract.js (hunk 2 above)
Comment (DaniSomoza) [reply apps/tx-builder/src/scripts/deploy-test-matrix-contract.js:24]: nice! makes sense! :3

Comment (DaniSomoza) [reply apps/tx-builder/src/scripts/deploy-test-matrix-contract.js:24]: I updated the hardhat configuration with your suggestion and now its the Final Fantasy! 

just with this command:

```
yarn contract:deploy-all rinkeby
```
or
```
yarn contract:deploy-all xdai
```
both contract are deployed and verified!

Captura de pantalla 2022-06-08 a las 14 20 35


in `gnosis chain` the command shows and error but the contracts gets verified and the ABI is automatically fetched from sourcify!!!! :D 

Captura de pantalla 2022-06-08 a las 14 21 10


Thanks! :3

File: apps/tx-builder/src/utils.test.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (DaniSomoza) [reply apps/tx-builder/src/utils.test.ts]: Done! I added a custom SoliditySyntaxError to address it!

**Comment by JagoFigueroa** [comment]
Hola guys, can confirm that the main issue (& why this ticket was created) has been fixed. 

I am now playing with the contracts testing every method to test the refactor itself which should take me a while. Here are my findings playing with the BasicTypesTestContract contract on Rin:

* testComplexTuple method is not working. Data is correct but it won’t validate on tenderly nor when sending the batch

* testArrayOfComplexTuple method not working. It wont specify any error for the data itself, tx is just reverted.

* testArrayOfTuples method is not working. It wont specify any error for the data itself, tx is just reverted

* testFunctionValue method is not working (or at least I have been able to fill the correct data for it to be added to a batch).

* testBytes16FixedArrayValue, testBytes2FixedArrayValue & testBytes1FixedArrayValue methods are not working for me. They should allow data like '0x' but they don't

Also, as a fun fact:

We

Screenshot 2022-06-14 at 16 17 27

Etherscan

Screenshot 2022-06-14 at 16 17 14

Super weird to say the least.

**Comment by DaniSomoza** [comment]
> Hola guys, can confirm that the main issue (& why this ticket was created) has been fixed.
> 

nice! Thanks!


> I am now playing with the contracts testing every method to test the refactor itself which should take me a while. Here are my findings playing with the BasicTypesTestContract contract on Rin:
> 
> * testComplexTuple method is not working. Data is correct but it won’t validate on tenderly nor when sending the batch
> * testArrayOfComplexTuple method not working. It wont specify any error for the data itself, tx is just reverted.
> * testArrayOfTuples method is not working. It wont specify any error for the data itself, tx is just reverted

We have [this separate ticket for the tuples](https://github.com/safe-global/safe-react-apps/issues/448). We need to research a little bit why how to address this issue.

> * testFunctionValue method is not working (or at least I have been able to fill the correct data for it to be added to a batch).
> * In general any method of fixed array type of bytes is not working for me.

I think that we can create a ticket to research how this weird callback types works on solidity:

```
    // function (callback)
    function(uint256) external functionValue;

    // function write methods
    function testFuntionValue(function(uint256) external callback) public {
        functionValue = callback;
    }


    // function read methods
    function getFunctionValue() public view returns (function(uint256) external) {
        return functionValue;
    }

```


> Screenshot 2022-06-14 at 17 02 30
> 
> Also, as a fun fact:
> 
> We
> 
> Screenshot 2022-06-14 at 16 17 27
> 
> Etherscan
> 
> Screenshot 2022-06-14 at 16 17 14
> 
> Super weird to say the least.

We found a lot of issues with Etherscan when we read some strange types, I think that we can use apps/tx-builder/src/hardhat/tasks/read_method.js to make sure that are sending the correct values to the blockchain.


Thanks! ❤️

**Comment by JagoFigueroa** [comment]
I will create those tickets, gracias Dani! The task was super useful for my testing.

All good with contract MatrixTypesTestContract so moving this ticket to QA Done ;)
