### PR TITLE
fix(safe-claiming-app): Fixes multiple issues with government widgets

### LINKED ISSUE #591: [safe-claiming-app]: voting power widget without any allocation / tokens
## Overview
Currently some dummy text is displayed for addresses without any allocated tokens.
We should show a meaningful message and remove the "buy tokens" button as this was just a placeholder.

## Requirements
- [x] Display instead:
```
*Become part of Safe’s future*
Help us unlocking ownership for everyone by joining the discussions in the SafeDAO Forum and our Discord.
```

### PR DESCRIPTION
**Pull request by schmanu**
## What it solves
Resolves #591 #590 https://github.com/safe-global/web-core/issues/1275

## How this PR fixes it
- removes buy-token-button
- rephrases text for no allocation
- fixes loading state to just a themed spinner
- goerli uses `tutis.eth` instead of `safe.eth`
- fixed size for voting power widget

## How to test it
- test governance widgets on goerli
  - use a safe without any tokens / allocation
  - use a safe which did not redeem all tokens yet
  - use a safe with token allocation
- when loading the app witness the spinner (only visible if network is slow)

### CODE REVIEW

File: apps/safe-claiming-app/src/hooks/useSafeSnapshot.ts [hunk 1]
```diff
@@ -76,7 +81,8 @@ const getSafeSnapshot = (amount: number): Promise<SnapshotProposal[]> => {
 }
 
 const useSafeSnapshot = (amount: number): AsyncResult<SnapshotProposal[]> => {
-  return useAsync(() => getSafeSnapshot(amount), [])
+  const { safe } = useSafeAppsSDK()
+  return useAsync(() => getSafeSnapshot(amount, safe.chainId), [])
```
Comment (iamacook) [inline apps/safe-claiming-app/src/hooks/useSafeSnapshot.ts:85]:
```suggestion
  return useAsync(() => getSafeSnapshot(amount, safe.chainId), [safe.chainId])
```

File: apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx [hunk 2]
```diff
@@ -113,14 +128,43 @@ const ClaimingWidget = () => {
   const ctaWidget = (
     <>
       <div>
-        <Title>Become the part of Safe's future!</Title>
+        <Title>Become part of Safe's future</Title>
         <br />
         <Subtitle>
-          You will be able to buy $SAFE once the token transferability is
-          enabled.
+          Help us unlocking ownership for everyone by joining the discussions in
```
Comment (iamacook) [inline apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx:134]:
```suggestion
          Help us unlock ownership for everyone by joining the discussions on
```

File: apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx [hunk 3]
```diff
@@ -113,14 +128,43 @@ const ClaimingWidget = () => {
...
+            variant="subtitle1"
+            textAlign="center"
+            fontSize="small"
+          >
+            SafeDAO Forum
+            <OpenInNewRounded
+              sx={{ width: "0.75em", height: "0.75em" }}
+              fontSize="small"
+            />
+          </StyledExternalLink>{" "}
```
Comment (iamacook) [inline apps/safe-claiming-app/src/widgets/ClaimingWidget.tsx:149]: I'd suggest creating a component for these as they are the same as each other. They can stay in this file though.

File: apps/safe-claiming-app/src/widgets/SnapshotWidget.tsx [hunk 4]
```diff
@@ -126,8 +128,10 @@ const SnapshotProposals = ({
 )
 
 const SnapshotWidget = () => {
-  const SNAPSHOT_LINK = "https://snapshot.org/#/safe.eth"
-  const FORUM_LINK = "https://forum.safe.global"
+  const { safe } = useSafeAppsSDK()
+  const snapshotSpace = CHAIN_CONSTANTS[safe.chainId]?.DELEGATE_ID
+
+  const SNAPSHOT_LINK = `https://snapshot.org/#/${snapshotSpace}`
```
Comment (iamacook) [inline apps/safe-claiming-app/src/widgets/SnapshotWidget.tsx:134]: Nit: you have the same logic in `getSafeSnapshot`. I'd move it to a helper function.
